import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { Footer } from "./components/footer/footer";
import { Header } from "./components/header/header";

import "./globals.css";
import "./embla.css";
import { cn } from "@/lib/utils";

const manrope = Manrope({ subsets: ["latin", "cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(manrope.className, "pt-[82px] lg:pt-[108px]")}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
